name: Deploy service (blue-green)

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      chartPath:
        required: true
        type: string
      containerPort:
        required: true
        type: number
      imageTag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: echo "service=${{ inputs.service }} chartPath=${{ inputs.chartPath }} port=${{ inputs.containerPort }} tag=${{ inputs.imageTag }}"
